version: '3.8'

services:
  php:
    build: .
    ports:
      - 8085:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: BLOG
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Load DDL and initial data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root