version: '3.8'

services:
  php:
    build: .
    ports:
      - 8085:80
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_DATABASE=BLOG
      - DB_TEST_DATABASE=BLOG_TEST

  mysql:
    image: mysql:8.0
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: BLOG
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql  # Load main DB schema and data
      - ./init-test-db.sql:/docker-entrypoint-initdb.d/2-init-test-db.sql  # Load test DB schema and data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root